name: Maven test and compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build and test
      run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging && cp -r target/site/apidocs staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging

